server:
    port: 0

spring:
    application:
        name: user-service
    kafka:
        consumer:
            valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
    cloud:
        stream:
            kafka:
                binder:
                    brokers: localhost:9092
                    zk-nodes: localhost:2181
            bindings:
                input:
                    destination: users
                    group: usergroup
                users:
                    consumer:
                        configuration:
                            value:
                                deserializer: org.apache.kafka.common.serialization.StringDeserializer