eureka:
    instance:
        prefer-ip-address: true
    client:
        enabled: true
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
