server:
    port: 0

spring:
    application:
        name: user-service
    cloud:
        stream:
            kafka:
                binder:
                    brokers: localhost:9092
                    zk-nodes: localhost:2181
            bindings:
                output:
                    destination: topic-jhipster
